### ISSUE TITLE
Not quite stylish formatting of named arguments.

### ISSUE THREAD

**Issue by MIvanchev** [brandonbloom/fipp#21]
Fipp, as well as pprint, doesn't seem to render named arguments correctly:

``` clojure
(foo :param1 "What a sunny day this is!"
     :param2 "Wait, which day is it again?"
     :param3 364)
```

Would be rendered as:

```
(foo
  :param1
  "What a sunny day this is!"
  :param2
  "Wait, which day is it again?"
  :param3
  364
```

I consider this an issue because there are well-known rules for formatting them.

**Comment by bhurlow** [comment]
@brandonbloom thanks for linking to your discussing here from the fipp docs. I understand fipp is targeting debugging use cases and not code formatting/refactoring. Can you point to any projects that do build off fipp (like puget) to target code formatting? Perhaps there are none, either way Fipp seems like it would be a good building block towards that goal

**Comment by brandonbloom** [comment]
I'm sure some exist, but I do not make use of any of them, so I can't point you in the right direction. Sorry.

**Comment by bhurlow** [comment]
@brandonbloom fair enough thnx!
