### ISSUE TITLE
Missing requirements?

### ISSUE THREAD

**Issue by cloojure** [brandonbloom/fipp#27]
Hi - Tried running the README example and I seem to be missing something. My project.clj already has  [fipp "0.6.2"]

~/cljtst > lein repl
nREPL server started on port 36876 on host 127.0.0.1 - nrepl://127.0.0.1:36876
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.7.0-alpha3
Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[fipp.engine :refer (pprint-document)])

FileNotFoundException Could not locate fipp/engine__init.class or fipp/engine.clj on classpath.  clojure.lang.RT.load (RT.java:443)
user=>

**Comment by brandonbloom** [comment]
Can you share your project.clj?

**Comment by rmoehn** [comment]
Just a guess: Clojure 1.7.0-alpha3 doesn't support reader conditionals yet? So it can't use the .cljc files in fipp 0.6.2. Try using 0.5.2.

(I guess you've found that out yourself by now or it just became obsolete. So this issue should be closed.)

**Comment by brandonbloom** [comment]
Yeah, I'll close this issue. Feel free to re-open if you have details and need further help.
