### ISSUE TITLE
deeply nested groups overflow the stack

### ISSUE THREAD

**Issue by bwo** [brandonbloom/fipp#28]
```
user=> (require '[fipp.engine :as e])
nil
user=> (def groups (first (drop 1000 (iterate (fn [x] [:group x]) [:text "hi"]))))
#'user/groups
user=> (e/serialize groups)

StackOverflowError   clojure.lang.Cons.next (Cons.java:39)
```

owing to the ping-ponging between `serialize` and `serialize-node` (so the same thing would presumably also occur for e.g. `span`.)

**Comment by brandonbloom** [comment]
Grumble grumble something something about tail calls. Patch welcome.

**Comment by brandonbloom** [comment]
Closing as I haven't seen this in practice and there is some evidence that related issues have been mitigated with recent versions of Clojure and/or JVM. Please speak up if others are hitting this in real scenarios. Thanks.
