### ISSUE TITLE
clojure 1.9 boolean? conflict

### ISSUE THREAD

**Issue by nha** [brandonbloom/fipp#40]
When using with clojure 1.9

WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: fipp.visit, being replaced by: #'fipp.visit/boolean?

https://github.com/brandonbloom/fipp/blob/f644b88329e09a61d33ad15b603856e74dc74039/src/fipp/visit.cljc#L31-L33

**Comment by brandonbloom** [comment]
Thanks for the report. This is being track here: https://github.com/brandonbloom/fipp/pull/39
