### ISSUE TITLE
Conflicts with Clojure 1.9 alphas

### ISSUE THREAD

**Issue by mtruyens** [brandonbloom/fipp#41]
I get the following warning with Clojure 1.9 (currently using Alpha 9, but several of the previous Alpha's had the same problem):

WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: fipp.visit, being replaced by: #'fipp.visit/boolean?

**Comment by brandonbloom** [comment]
Thanks for the report. This is being tracked here: https://github.com/brandonbloom/fipp/pull/39
