### ISSUE TITLE
question - how to print edn with two space indentation?

### ISSUE THREAD

**Issue by shaunlebron** [brandonbloom/fipp#54]
I just want to uniformly change the edn's default indentation length to 2 instead of 1.

**Comment by brandonbloom** [comment]
There's no configuration exposed for this either the edn/clojure formatters or the primitive's default parameters. However, the indentation already uses two space indents, not one. If you're seeing only one space anywhere, it's when there's vertical alignment with the default offset of zero.

If you're seeing unexpected behavior, please re-open this issue with more details regarding reproduction and expected results.
