### ISSUE TITLE
Just a small warning in CLJS (undeclared var `fipp.edn/*file*`)

### ISSUE THREAD

**Issue by alexandergunnarson** [brandonbloom/fipp#59]
Getting this error in Figwheel:

```
[Figwheel:WARNING] Compile Warning: Use of undeclared Var fipp.edn/*file*  generated/dev/public/js/generated/fipp/edn.cljc   line:111  column:45
```

This is due to the `fipp.edn/dbg` macro being added but not being conditionalized to `:clj` (or at very least `*file*` being conditionalized somehow).

**Comment by brandonbloom** [comment]
Thanks for the report. I haven't used ClojureScript in a while. Can you try changing `*file*` to `#?(:clj *file*)` and see if the `dbg` macro works for you in Clojure? If so, I'll ship that. If not, I'll remove `dbg` from the ClojureScript build for now, unless somebody wants to make `dbg` work
