### ISSUE TITLE
Optional println?

### ISSUE THREAD

**Issue by venantius** [brandonbloom/fipp#61]
I was wondering if you'd be open to making the newline generated here optional: https://github.com/brandonbloom/fipp/blob/master/src/fipp/engine.cljc#L245. This is motivated in part by my looking for naive workarounds to this - https://github.com/greglook/whidbey/issues/30; let me know if I'm just barking up the wrong tree here.

**Comment by brandonbloom** [comment]
I can't think of any situation where I wouldn't want a trailing newline in pretty-printed output. Other than, of course, when somebody else is already providing one.

My intuition is that the newline should be non-optionally excluded downstream (nrepl or wherever), not made optional here in Fipp.

Let me know if you think that this is way off base.
