### ISSUE TITLE
Make usage of commas optional

### ISSUE THREAD

**Issue by jeluard** [brandonbloom/fipp#63]
Pretty-printing maps uses commas.

Would you consider a PR to make the usage of commas optional?

**Comment by brandonbloom** [comment]
Could you please elaborate on why you want this?

**Comment by jeluard** [comment]
I'm using fipp to pretty print some EDN and render it to a web page.
For cosmetic reasons I'd rather not have some commas.

Does this use case makes sense for fipp?

**Comment by brandonbloom** [comment]
Yes and no. I’m not planning on adding output preferences of any kind to
the built in pretty implementation. However, the implementation is very
small and both the ednize and printing engine are reusable. I suggest you
create your copy/paste and tweak to your hearts content.
