### ISSUE TITLE
consider automating tests on circleci

### ISSUE THREAD

**Issue by lread** [brandonbloom/fipp#68]
Hello!

Before working on #66, I found #67 and this made me wonder if you'd be interested in automating the running of tests on [circleci](https://circleci.com/).

As part of this work I propose: 
1. integrating cljs tests into lein via [lein-cljsbuild](https://github.com/emezeske/lein-cljsbuild).
2. creating a circleci config that would automatically run tests on commit.

I don't know that automatically running the benchmark would be of interest/value, I guess it would test that it still works.

**Comment by lread** [comment]
Also to consider for a test runner is [kaocha](https://github.com/lambdaisland/kaocha).  Note though that it has a minimum requirement of clojure 1.9 and I guess that would be a showstopper for you if you want to still want to support clojure 1.8.

**Comment by brandonbloom** [comment]
I'm not interested in adding any more tooling for a project this small and infrequently updated. Thanks though.

**Comment by lread** [comment]
Fair enough! I totally understand one person's gift can be another person's burden and respect your choice.
