### ISSUE TITLE
print-table of nested map

### ISSUE THREAD

**Issue by awb99** [brandonbloom/fipp#70]
Can I do something like

```
(print-table [ {:a {:b 1 :c 2} :d 3}  {:a {:b 4 :c 5} :d 6} ]
                  [ [:a :c]  :d] )
```

Result would be
```
:a :c     +  :d
+++++++++++++++
2         +  3
5         +  6
```

Nested maps are not supported by clojure.pprint/print-table
And I didn't find any other lib that would allow me to do that.

**Comment by brandonbloom** [comment]
Fipp doesn't do table layouts and there are no plans to add support for it. Table layouts require arbitrary-lookahead to decide how wide to make columns. Such unbounded needs are at odds with this project's performance goals.
